### ISSUE TITLE
ARM64: PyTest -> Integration Tests -> `Azure`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1037]
Meta Issue: #1028 

## PyTest
This issue covers the validation of `integration tests` of PyTest for the platform provider `Azure`  running on `ARM64` / `AARCH64` architectures.

## Tests
Within this issue the following components will be validated and tested:
- PyTest
  - Integration Tests
    - `Azure`

**Comment by nanory** [comment]
Hi @gyptazy,

as of now, Azure does not have publicly available ARM instances, so we can not perform those tests for now:
* https://azure.microsoft.com/en-us/updates/public-preview-arm64based-azure-vms-can-deliver-up-to-50-better-priceperformance/

Let us put this issue on waiting until we have access to Azure ARM instances.

**Comment by chrinorse** [comment]
I extended the Azure integration test to be able to create an arm64 VM. On my first try to run the integration tests, Azure show a synchronous exception when booting the VM.

![vm-gl-test-20220921141757 2f8757d6-994d-43a7-b70d-03e64cbb6713 boot-diagnostics-arm64-boot screenshot](https://user-images.githubusercontent.com/53080514/191686320-016f11df-061e-47aa-8daf-04a02d09a3a2.jpg)

**Comment by nanory** [comment]
Hi everyone,

this issue got closed due to the merge of PR #1291, however it seems that we still have a problem with the boot partition, which has temporarily been solved by PR #1311. 

Nevertheless, the first change of this issue has been reverted because of this. It seems that it also creates a Unified Image for legacy. We must analyze the issue and create a proper fix for it.

**Comment by nanory** [comment]
After having a meeting about this issue, I would like give the newest updates to it.

For now, we will put this issue on hold because the change introduces an Unified Image for all Garden Linux variants. The build scripts which are used to create a EFI partition have been streamlined by this change.

However, in order to make Garden Linux work with Microsoft EFI Boot, the EFI partition now contains a Unified Image containing the initrd and kernel. The build pipeline makes no difference between different flavours, so the Unified Image is always added.

This is problematic, because Garden Linux still supports legacy boot for AMD64 machines, so both booting variants can be used. This doubles the required size for the EFI partition because it contains the legacy bootloader (syslinux), the kernel, initrd and a Unified Image for UEFI, which again contains the initrd and the kernel.

We could either ensure that only one boot variant is available within a Garden Linux image which makes us lose flexibility but ensures that the size isn't doubled or we need to clarify if this Unified Image is always required.

For this reason, we will have another meeting on 25th of October, in which we will discuss if Azure really requires Unified images to boot properly on EFI or if we could solve it differently. Other plattforms do not require Unified Images which contain the kernel and initrd to boot properly for example.
