### ISSUE TITLE
ARM64: PyTest -> Integration Tests -> `GCP`

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1039]
Meta Issue: #1028 

## PyTest
This issue covers the validation of `integration tests` of PyTest for the platform provider `GCP`  running on `ARM64` / `AARCH64` architectures.

## Tests
Within this issue the following components will be validated and tested:
- PyTest
  - Integration Tests
    - `GCP`

**Comment by nanory** [comment]
Hi @gyptazy,

as of now, GCP does not support ARM machines so we can not perform integration tests of these kinds of images:
* https://cloud.google.com/compute/docs/cpu-platforms

However, we should probably add a proper error message because as of now, the pytests waits for the VM instance to start in order to perform the corresponding tests but the VM won't start.

**Comment by nanory** [comment]
We will leave it as it is for now and close this issue
