### ISSUE TITLE
SecureBoot: Different `enroll-gardenlinux-secureboot-keys` files in features

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#1105]
**What happened:**
The used file for `enroll-gardenlinux-secureboot-keys` may vary depending on the used feature.
e.g.:
`metal:` https://github.com/gardenlinux/gardenlinux/blob/main/features/metal/file.include/usr/sbin/enroll-gardenlinux-secureboot-keys
`cloud:` https://github.com/gardenlinux/gardenlinux/blob/main/features/cloud/file.include/usr/sbin/enroll-gardenlinux-secureboot-keys

We should only have a single file that is getting maintained.

**Comment by nanory** [comment]
I had to re-open this issue because PR #1106 does not fix the mentioned issue here. Using a symlink does not work in `file.include` since the build will simply place the symlink in the Garden Linux image, so that it contains an unresolvable symlink.

As of now, we should simply copy the newest version in both features and move on in #1107 in which we want to create a dedicated `secureboot` feature.

**Comment by gyptazy** [comment]
Will be fixed by #1109
