### ISSUE TITLE
Garden Linux version number is always today

### ISSUE THREAD

**Issue by MrBatschner** [gardenlinux/gardenlinux#1119]
**What happened:**

Building a Garden Linux image results with version number `today` (and commit-id `local`) in `/etc/os-release`.

```
root@gardenlinux:/# cat /etc/os-release  
PRETTY_NAME="Garden Linux today"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://gardenlinux.io/"
SUPPORT_URL="https://github.com/gardenlinux/gardenlinux"
BUG_REPORT_URL="https://github.com/gardenlinux/gardenlinux/issues"
GARDENLINUX_FEATURES=_slim,base,server,cloud,aws,gardener
GARDENLINUX_VERSION=today
GARDENLINUX_COMMIT_ID=local
VERSION_CODENAME=today
```

**How to reproduce it**:
- build an image (e.g. `make aws`)
- examine `/etc/os-release` for the version number
 
**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | *main* @ 5f1a6c3f7ece9e33a852462b3a2b885d693c338f |
| Container runtime (version)  | *docker* | 
| Host OS of build machine  | *Linux* |

**Comment by Vincinator** [comment]
A fix for this issue (#1119) might be affecting issue #460

**Comment by gehoern** [comment]
if you build for today (or yesterday, last week or all the short names of linux `date`) this results in the respective date name: e.g. today is gardenlinux day 849 then every where you would write such ans acronym you would use 849. e.g. in os-release in the mot.d ...
BUT there is one special case: if you use TODAY (only this) then the generation of the url for apt source is NOT replaced. (use case: you build for today then you wanna know the version it is actually but you want to make sure it stays in our repo up-to-date - the only repo that provides this is the repo "today" / if you build for a certain date e.g. 576 then of course all version remarks are on 576 yes AND the download url must also refer to a repo named 576 -> so gardenlinux is pinned to this version)
the implicit result is the daily build is never against today ... the daily build is against the date of yesterday (but not the literal) but if you build yourself a dev version - created on your build env, fur you dev usage -> this will stay up-to-date because this build goes against the literal "today"

**Comment by Vincinator** [comment]
See [bin/garden-version#L55](https://github.com/gardenlinux/gardenlinux/blob/99d749072e963ce16af7b0f63e241983adc07bb0/bin/garden-version#L55 )
