### ISSUE TITLE
Add Python requirements.txt

### ISSUE THREAD

**Issue by notandy** [gardenlinux/gardenlinux#1535]
**What would you like to be added**:

Apart from some documented coreutils, apparently gardenlinux build chain needs some python libraries to work which are not documented in the README.

My suggestion is to add a root dir [requirements.txt](https://pip.pypa.io/en/stable/reference/requirements-file-format/) for PIP which can have the most current list of requirements like pyyaml, networkx, azure/gcp/aws/alicloud sdk etc.. 

**Why is this needed**:
To automatically install required libraries needed to use the toolchain. This makes it easier to maintain automatic pipelines.

**Comment by gyptazy** [comment]
Hey @notandy,

thanks for this feedback. May I ask, how did you encounter this issues? I'd assume that you were trying to run the build pipeline (or integration test, because you especially mentioned the hyperschaler SDK's) locally on your workstation, but the whole build process is done in containers.

**Testing**
Garden Linux provides a [base-test](https://github.com/gardenlinux/gardenlinux/tree/main/container/base-test) and the full fledged [integration-test](https://github.com/gardenlinux/gardenlinux/tree/main/container/integration-test) container. While the [base-test](https://github.com/gardenlinux/gardenlinux/tree/main/container/base-test) one is just for running the basic tests like unit tests, the [integration-test](https://github.com/gardenlinux/gardenlinux/tree/main/container/integration-test)  container may be used to test everything including the hyperschaler integration tests (see also the [Dockerfile](https://github.com/gardenlinux/gardenlinux/blob/main/container/integration-test/Dockerfile#L7-L36).) Within its [Dockerfile](https://github.com/gardenlinux/gardenlinux/blob/main/container/integration-test/Dockerfile#L7-L36) you can see that all needed dependencies are solved and installed.

Since you also mentioned `pyyaml` and `networkx` which just recently came up with https://github.com/gardenlinux/gardenlinux/commit/57591b43e1bd6c73c5cc3bb862f2b06725775f74 are already documented. Any other ones shouldn't be needed on the local build environment and further dependencies should be included by the related containers. I think a `requirements.txt` could optionally be added but we since these packages are included in almost all distributions we should still prefer the distributions package manager instead of pip. However, to be safe for all eventualities this could be added.

Looking forward to hear from you!
Have a nice weekend!

Cheers,
gyptazy
