### ISSUE TITLE
gardenlinux kernel headers common deb package missing

### ISSUE THREAD

**Issue by dnlvanco** [gardenlinux/gardenlinux#2067]
**What happened:**
gardenlinux kernel headers common deb package missing

**Debug Logs:**
N/A

**How to reproduce it**:
try to install gardenlinux kernel headers package you will get missing dependency error.
Package is present in upstream debian - all ok.
 
**Environment:**

| Name | Value |
| ------------------- | ----- |
| Garden Linux Branch | *main* |
| Container runtime (version)  | N/A | 
| Host OS of build machine  | N/A | 

**Anything else we need to know**:
- *e.g. last time it worked without the bug?* 
- *e.g. link to your garden linux fork*
- *e.g. tested on other build environments*

**Comment by Vincinator** [comment]
Hi @dnlvanco,

you can install kernel headers with `linux-headers-amd64` or `linux-headers-arm64` depending on your CPU architecture.

But you are right, there is a meta package missing, so that you can simply install `linux-headers` and it depends on the correct architecture type. This is a perfectly valid enhancement request. 
Let me know if this works for you, or you have further questions.

**Comment by Vincinator** [comment]
More context for this enhancement request: 

Currently, we have this dependency chain:

`linux-headers-amd64` -- depends on -> `linux-headers-6.6.22-amd64` 


and `linux-headers-6.6.22-amd64` depends on the following list:
```
  Depends: linux-headers-6.6.22-common (= 6.6.22-0gardenlinux0)
 |Depends: linux-image-6.6.22-amd64 (= 6.6.22-0gardenlinux0)
  Depends: <linux-image-6.6.22-amd64-unsigned> (= 6.6.22-0gardenlinux0)
  Depends: linux-kbuild-6.6.22
  Depends: gcc
``` 


we should also add a `linux-headers` meta package that just depends on the correct `linux-headers-6.6.22-<ARCH>`
