### ISSUE TITLE
2024-06-25 Nighly needs to be fixed

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2170]
Nighly failed. See https://github.com/gardenlinux/gardenlinux/actions/runs/9657247720

**Comment by pnpavlov** [comment]
@Akendo takes a look together with another related task. If help needed go to @Vincinator .

**Comment by Akendo** [comment]
We've updated the package. However, we need to deal with some dependency problem installing gcc. Continue on later on.

**Comment by nkraetzschmar** [comment]
ok, reverting the repo to use debians binutils to keep gcc and other dependecies and we'll just build the kernel using an older snapshot of build tooling.
There shouldn't be any dependencies between the versions of tooling used during kernel build and in user space => shouldn't cause any issues

**Comment by nkraetzschmar** [comment]
kernel build in progress: https://github.com/gardenlinux/package-linux/actions/runs/9676151329
package-binutils removed => will revert to debian import on next repo build

**Comment by Akendo** [comment]
The problem we observed is that with the package-binutilites we run into dependency problem with GCC. Since we do not want to maintain GCC separately, we decided to fix this by using an older container to build the necessary kernel module. There is a risk involved that the broken binutilies in our nightly builds might produce broken binaries, for instance kernel modules. However, we do not see that we have users that might become affected by this for now. 

We test this once our change has been fixed. We will build a kernel module. However, once completed, we think it's going to be fixed. 

We should be aware that as long we have a broken state binutiles, we can't perform proper releases. We think that we might have corrupt binaries files and have either to wait for upstream fixes or use the latest nightly without these changes.

**Comment by fwilhe** [comment]
For reference: From the debian bug, they also liked an upstream issue now https://sourceware.org/bugzilla/show_bug.cgi?id=31924

**Comment by nkraetzschmar** [comment]
side note on the underlying root cause:

I've so far been able to likely triangulate the issue down to the step from `vmlinux.o` to `vmlinux`.
Using the broken version of binutils it produces `.relr.dyn` sections which older versions did not produce at all and the `.rela.dyn` section gets significantly smaller (which makes sense as relr should be more space efficient then rela).
However, it looks like the kernel builds with `RELR=n`, likely because `TOOLS_SUPPORT_RELR=n`.

So my current hypothesis is that ld / objcopy create a kernel image that would need relr support, while it is not actually supported kernel side.
