### ISSUE TITLE
Research Secureboot on MS Azure (stage0)

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2287]
Research and document in this issue how secureboot on GCP can be enabled.

- [ ] What are the prerequisites?
- [ ] What steps are required?
- [ ] Are there any risks or limitations?
- [ ] Are there configurations that need to be performed by the user to use the image?

**Comment by mguertler** [comment]
### Overview

Azure Secure Boot and Trusted Boot features are summarized as [Trusted Launch](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch) features. They include Secure Boot, TPMv2 support and Integrity Monitoring, similar to AWS and GCP. Trusted boot is supported for certain Operating Systems (see below) from the Azure Marketplace, but also as Azure Gallery images and VHDs.

### Limitations

In Azure it is currently not possible Trusted Launch for non-supported Operating Systems, as it is possible with AWS and GCP using custom signed images. [Only some Operating Systems like Debian, SUSE, RedHat, Ubuntu are supported with Trusted Launch features](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch#operating-systems-supported). The images of these OS's are  signed using the Microsoft 3rd party CA certificates.

Furthermore only Generation 2 VMs are supported.

### Custom signed kernel drivers and modules

From 08/22/2024 there is a preview feature ["Secure Boot UEFI keys"](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-secure-boot-custom-uefi) available, that allows kernel drivers / modules to be signed with custom private keys. This feature allows to inject custom UEFI keys into the vTPM and thus allows checking the validity of kernel modules during boot time. However, this feature can't be used to enable secure boot for non-Micrsoft-signed OS's like GL, nor is this supported, neither it seems to work technically.

**This feature has some limitations:**
 
* Only usable for SIG images, created from Trusted Launch VM VHDs, that again must be derived from Trusted Launch enabled OS images
* Requires Gen2 VMs
* Requires ARM (Azure Resource Manager); According to the [corresponding documentation](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2024_07_01.models.uefisettings?view=azure-python) there is no possibility, to use the Python interface to enable this feature, which would be required by the current mechanisum of the GL platform tests
* Can not be used to enable secure boot for non-Microsoft-signed OS's

### Decision options (draft)

1. Leave GL secure boot / trusted boot disabled for GL
Pro's:
* no effort
Con's:
* inconsistent secure-boot support across hyperscalers
* might be rejected by external stakeholders, like Gardener

2. Ask Microsoft to provide support for custom signed GL images
Pro's:
* allows to enables secure boot / trusted boot
* fits perfect to current build and testing schemes of GL
* provides consistent secure boot / trusted boot support across hyperscalers
* Might fulfill requirements of external stakeholders like Gardener
Con's:
* Likely a bigger / longer discussion, as it might result in a fundamental decision Microsoft internally; However, SAP is an important partner for Micrsoft

3. Agree with Microsoft to sign GL images with Microsoft 3rd party CA certificates
Pro's:
* allows to enables secure boot / trusted boot
* provides consistent secure boot / trusted boot support across hyperscalers
* Might fulfill requirements of external stakeholders like Gardener
Con's:
* Requires deriving GL signing process just for Azure images
* GL might require to undergo a formal certification process

### Asks to Microsoft

1. Are there any plans to support custom signed images for OS's to enable them for Azure Trusted Launch (e.g. secure boot), as this feature is already provided by GCP and AWS
2. What are efforts to sign a new Linux OS with the Microsoft 3rd party CA certificates
3. Are there any other options, that Microsoft can provide to enable Trusted Launch features for Garden Linux, at least for Azure environments that are used by SAP

**Comment by mguertler** [comment]
## Outcomes of discussion with Microsoft

We had a discussion with Microsoft and received the information that the [Secure Boot UEFI preview feature](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-secure-boot-custom-uefi) should work for all custom signed components of a Secure Boot enabled Linux distribution. It just isn't documented in the preview feature configuration guide right now. Using that information, further testing has been performed.

## Further testing and debugging

Further tests where finally successful and Azure Gen2 VMs using a custom signed GL image could be started with enabled Secure Boot (Trusted Launch in Azure).

The guide of the preview feature includes a configuration step, where the Secure Boot DB certificate is converted into the Base64 format. The guide describes a command line snippet, that strips the header and the footer of the Base64 encoded certificate. However, also the newlines characters have to be stripped in order to get a correct Base64 UEFI vars string. The parameter parser in Azure doesn't recognize this error, which results in a build of an SIG image using a corrupt DB certificate. When using this image to start a secure boot enabled Gen2 VM, it leads to an error message, stating that "one or more components of the Operating System are not signed".

After providing a clean Base64 UEF vars string, the newly created Azure SIG image could be used to successfully start a Secure Boot enabled VM running GL.

## Final results

Using the [Secure Boot UEFI preview feature](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-secure-boot-custom-uefi) It is possible to create custom signed Azure SIG images for Garden Linux. Gen2 VMs using these images can be successfully started with enabled Secure Boot (Trusted Launch in Azure). Both Secure Boot related GL features (_trustedboot and _tpm) have been tested and are working as expected.

## Next steps

- Redo the image creation steps using the Azure command line utility "az" and the provided ARM deployment template
- Implement this feature in the Garden Linux build process and platform tests.

## Possible issues

The current workflow for creating custom signed SIG images is only described using an Azure ARM deployment template. However,. the [platform setup for Azure](./tests/platformSetup/azure.py) in Garden Linux is entirely relying on the Azure API using the [Microsoft Azure SDK for Python](https://pypi.org/project/azure/). In the [Azure API documentation](https://learn.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2024_07_01.models.uefisettings?view=azure-python) however, there is no parameter described, how to pass the Base64 encoded DB certificate to Azure for an image build process. It has to be clarified with Microsoft if it is possible to use the Azure API for that step.

**Comment by pnpavlov** [comment]
Research done -> feasibility confirmed. Let's continue with Enable Secureboot images on MS Azure (stage0) [#2286](https://github.com/gardenlinux/gardenlinux/issues/2286)
