### ISSUE TITLE
Fix Nightly GL 1604

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2294]
From https://gardenlinux.github.io/daily/ GL 1604 failed with

![Image](https://github.com/user-attachments/assets/7f565e1c-ae5f-4123-b89c-dc0e3a9505e4)

**Comment by Vincinator** [comment]
two issues
1) repo build failed due to an internal github server error (re-run fixed it)
2) package repos failed, but no version upgrades since yesterday. From tomorrow on, this issue should not happen again thanks to https://github.com/gardenlinux/package-build/pull/8


We do not need to re-build the failed packages for 1604 nightly, reason below:
* package-openssh 
    * ✅ based on 1:9.8p1-2, no version change since yesterday
* package-cyrus-sasl2
    * ✅ based on 2.1.28+dfsg1-7, no version change since yesterday
* package-ignition
    * ✅ using 2.19 from upstream, we merge in some stuff from debian if i see it right. I think we are good here for a nightly as well
* package-pam
    * ✅ based on 1.5.3-7, no version change since yesterday
* package-refpolicy
    * ✅ based on 2:2.20240723-2, no version change since yesterday
