### ISSUE TITLE
Maintain (active) releases in machine readable form

### ISSUE THREAD

**Issue by fwilhe** [gardenlinux/gardenlinux#2296]
**What would you like to be added**:
The linux kernel maintains a file at https://www.kernel.org/releases.json where releases are present in a machine-readable form.
This is pretty nice for automation purposes.
We could do something similar, creating such a file could be done by our release-notes workflow.

**Why is this needed**:
In automation, we sometimes need to know (maintained) Garden Linux versions.
We can use git tags or github releases in this repo, but this is missing some information/meta data.

This could be useful to provide a similar view to https://packages.debian.org/search?suite=all&searchon=names&keywords=wget where we want to know the package versions present in (relevant) Garden Linux versions.

This could also be useful for GLVD.

Just a rough sketch of what this file could look like:

```json
{
    "releases": [
        {
            "moniker": "something-needs-to-be-aligned",
            "version": "1592.1",
            "iseol": false,
            "released": {
                "timestamp": 1724569631,
                "isodate": "2024-08-25"
            }
        },
        {
            "moniker": "something-needs-to-be-aligned",
            "version": "1592.0",
            "iseol": true,
            "released": {
                "timestamp": 1724569631,
                "isodate": "2024-08-25"
            }
        },
        {
            "moniker": "something-needs-to-be-aligned",
            "version": "1443.10",
            "iseol": false,
            "released": {
                "timestamp": 1724569631,
                "isodate": "2024-08-25"
            }
        }
  ]
}
```

**Comment by pnpavlov** [comment]
@yeoldegrove would that help you instead of :latest cat /etc/os-release?

**Comment by yeoldegrove** [comment]
@pnpavlov @fwilhe

https://github.com/gardenlinux/gardenlinux/commit/87e2dc920e906345d19b19a40c78b08d5af8e389#diff-9dd0c2a02c4e49d2c385f2033fa07902c78b11ef7013e8fbfbf90d19d6e6057c would be a quick hack to parse `ghcr.io/gardenlinux/gardenlinux:latest` and extract the actual release tag.

```
❯ bin/garden-version-latest
1592.1
```

**Comment by pnpavlov** [comment]
@yeoldegrove , please check if this is in same direction as your current work? Can we do that?

**Comment by fwilhe** [comment]
Alternative suggestion for file layout

The idea here would be to group releases by major versions (one new every day) and to mark which of those are 'maintained', i.e. get any patch releases. I'm not sure if this adds much value, or if we should leave out those nightly releases.

```json
{
    "releases": [
        {
            "major": "1602",
            "isMaintained": false,
            "patches": []
        },
        {
            "major": "1592",
            "isMaintained": true,
            "patches": [
                {
                    "version": "1592.1",
                    "iseol": false
                },
                {
                    "version": "1592.0",
                    "iseol": true
                }
            ]
        },
        {
            "major": "1443",
            "isMaintained": true,
            "patches": [
                {
                    "version": "1443.10",
                    "iseol": false
                },
                {
                    "version": "1443.9",
                    "iseol": true
                }
            ]
        }
    ]
}
```

Alternatively it might also look like this where we add only the maintained major versions.
The individual objects should each have more information than in this example, i.e. release date, etc.

```json
{
    "releases": [
        {
            "major": "1592",
            "patches": [
                {
                    "version": "1592.1",
                    "iseol": false
                },
                {
                    "version": "1592.0",
                    "iseol": true
                }
            ]
        },
        {
            "major": "1443",
            "patches": [
                {
                    "version": "1443.10",
                    "iseol": false
                },
                {
                    "version": "1443.9",
                    "iseol": true
                }
            ]
        }
    ]
}
```

those suggestions leave out qualifiers like 'longterm' etc, I don't really think this makes sense in our case, but I'm open to challenge this.

After an initial file was hand-crafted, updates of this file should be possible to do fully automated in our ci pipeline. The needed information should be available there.

**Comment by pnpavlov** [comment]
for the SapMachine use-case it is required to be able to understand:
- what are current releases 
- which is the latest release
- is the release in maintenance 

fmi Christian (SapMachine)

**Comment by yeoldegrove** [comment]
Instead of having a split between `releases_stable` and `releases`, one could also define `type: 'stable'` and `type: 'patch'`.

**Comment by fwilhe** [comment]
Hi @yeoldegrove, I think this looks good 👍 

Things to note: We do sometimes 'burn' patch versions, i.e. that version 1443.7 exist does not imply that version 1443.6 exists. It might or it might not.

For this reason, I'd like to have a complete list of patch releases in that release file. I don't think this contradicts what you said, just to make this explicit.

I'm not sure how certain we are with those release and support timeframes, this falls into the responsibility of @pnpavlov. Would you be fine with this?

For GLVD specifically, what I want are mostly two things:

I'd like to have an automated way to know what the 2 or 3 or 4 current versions are (i.e. the latest patch release of the last few major releases). I think this is covered by your suggestion. Those should be prominently featured in the GLVD user interface.

Second, for all released versions (this excludes the 'burned' patches mentioned above), I need a way to construct the url for getting the list of packages. Essentially all information i need for that is a list of version numbers, so a structure like `1443: [1443.0, 1443.1, 1443.2 ..], 1592: [1592.0, 1592.1, ..]` would be good enough for that.

This extended life-cycle information might also be useful, for example the GLVD cli tool or web ui might be able to warn users about 'you are using version that does not get any security fixes, please upgrade asap'. I think this is useful, if we have a meaningful definition of those support timeframes.

**Comment by yeoldegrove** [comment]
@fwilhe If you burn a patch version, is it supposed to be found later or is it supposed to "just not exist"? In the later case the patch release just has to be removed and it will never be found again. Another possibility to flag this as burned would be setting the eol date to the same date as the release date or deleting the release date.

I am still not fond of the idea to reference the patch versions in the stable version's entry (e.g. having a `version.patches: [1443.0, 1443.1, 1443.2]`) field. The whole point of having a naming scheme like ${major}.${minor} is that it is clear which version is the parent. This does not need a reference field or are there any good arguments for this? If I want to have all patches for a release I can build that filter/query into the client that queries the "release database".

**Comment by yeoldegrove** [comment]
This is my latest take on how to define releases and their schemas. Based on the discussions above and our current documentation.

## Releases in general (from https://github.com/gardenlinux/gardenlinux/blob/main/docs/00_introduction/release.md)

You can expect up to four Garden Linux releases per year, published up to once per quarter. A new release _(e.g. 1443.0 or "release 1443")_ includes major changes like newer major version of software package or library. Within a release maintenance period (release date -> End-of-life date), changes are published as release patches _(e.g. 1443.1 or "patch 1 of release 1443")_. Each release is maintained nine months, while going through following maintenance phases:

- **Standard maintenance** starts with the publishing of a new stable release and continues for six months. In this phase active maintenance is performed on the release. You can expect regular patches including _(but not limited to)_ fixes for issues, updates to higher minor release of selected software packages and libraries included, proactive monitoring & assessment of security vulnerabilities, performance corrections and enhancements and more. General best practice is to always use the latest patch of the latest release.

- **Extended maintenance** starts after the standard maintenance phase and continues for three months. In this phase only [Common Vulnerabilities and Exposures (CVE)](https://csrc.nist.gov/glossary/term/common_vulnerabilities_and_exposures) with high and critical (7.0-10.0) severity according to the [Common Vulnerability Scoring System (CVSS)](https://nvd.nist.gov/vuln-metrics) are patched. For more details refer to the [Garden Linux Security Response Process](/SECURITY.md). This enables users to have sufficient time to plan and execute their transition to latest release in standard maintenance.

- **End of maintenance** is reached nine months after the release has been published. In this phase no further planned maintenance activities are performed. Adopters can continue to use the release at their own risk. Users can request an exceptional patch via GitHub issue in [gardenlinux](https://github.com/gardenlinux/gardenlinux/issues/new/choose). There is no guarantee the request will be served - maintainers reserve the right to reject the request and fix-forward only in the latest release that is in standard maintenance due to the complexity involved with producing a patch for very old release.

## Release Schema

The Garden Linux Release Database (GLRD) uses structured JSON schemas to represent different types of releases: **stable**, **patch**, **nightly**, and **development** releases. Each release type has specific fields that capture essential information about the release.

### Stable Releases

Stable releases are major releases that are supported over an extended period of time (see above).

#### Schema Fields

- **`name`**: A string representing the release name (e.g., `release-1312`).
- **`type`**: `stable`.
- **`version`**:
  - **`major`**: An integer indicating the major version number (e.g. `1312`).
- **`lifecycle`**:
  - **`released`**:
    - **`isodate`**: The release date in ISO format (`YYYY-MM-DD`).
    - **`timestamp`**: The UNIX timestamp of the release date.
  - **`extended`**:
    - **`isodate`**: Optional extended maintenance date in ISO format.
    - **`timestamp`**: Optional UNIX timestamp for the extended maintenance date.
  - **`eol`**:
    - **`isodate`**: End-of-life date in ISO format.
    - **`timestamp`**: UNIX timestamp for the end-of-life date.

### Patch Releases

During the standard and extended maintenance periods the corrections are delivered via patch releases ("patches"). They are considered stable, and adopters are encouraged to always use the latest patch of the latest stable release. Patch releases can be expected to adhere to following rules:

- Can include higher minor versions of software packages or libraries already included in the LTS release.
- Can include security enhancements related to vulnerabilities identified after the release of the previous patch.
- Can remove in rare (exceptional) situations software packages or libraries (e.g. due to security or legal risk identified after the release was published.). Such changes are documented in the release note.

#### Schema Fields

- **`name`**: A string representing the release name (e.g., `release-1312.1`).
- **`type`**: `patch`.
- **`version`**:
  - **`major`**: An integer indicating the major version number (e.g. `1312`).
  - **`minor`**: An integer indicating the minor version number (e.g. `1`).
- **`lifecycle`**:
  - **`released`**:
    - **`isodate`**: The release date in ISO format.
    - **`timestamp`**: The UNIX timestamp of the release date.
  - **`eol`**:
    - **`isodate`**: End-of-life date in ISO format.
    - **`timestamp`**: UNIX timestamp for the end-of-life date.
- **`git`**:
  - **`commit`**: The full git commit hash associated with the release.
  - **`commit_short`**: The short git commit hash (first 7 characters).
- **`github`**:
  - **`release`**: The URL to the GitHub release page.

### Nightly Releases

Nightly releases are automated builds that are generated every night, reflecting the latest state of the codebase.

#### Schema Fields

- **`name`**: A string representing the release name (e.g., `nightly-1312.0`).
- **`type`**: `nightly`.
- **`version`**:
  - **`major`**: An integer indicating the major version number.
  - **`minor`**: An integer indicating the minor version number.
- **`lifecycle`**:
  - **`released`**:
    - **`isodate`**: The release date in ISO format.
    - **`timestamp`**: The UNIX timestamp of the release date.
- **`git`**:
  - **`commit`**: The full git commit hash associated with the release.
  - **`commit_short`**: The short git commit hash.

### Development Releases

Development releases are used for testing and development purposes, representing the latest changes that may not yet be included in a stable or patch release. These can be manually created by developers.

#### Schema Fields

- **`name`**: A string representing the release name (e.g., `dev-1312.0`).
- **`type`**: `dev`.
- **`version`**:
  - **`major`**: An integer indicating the major version number.
  - **`minor`**: An integer indicating the minor version number.
- **`lifecycle`**:
  - **`released`**:
    - **`isodate`**: The release date in ISO format.
    - **`timestamp`**: The UNIX timestamp of the release date.
- **`git`**:
  - **`commit`**: The full git commit hash associated with the release.
  - **`commit_short`**: The short git commit hash.

### Lifecycle Dependencies

The lifecycle fields in the release schemas help track the release dates and end-of-life (EOL) dates for each release. There is a dependency between the `lifecycle` fields of **stable** and **patch** releases:

- **EOL of Patch Releases**: The `eol` date of a patch release is set to the `released` date of the next patch release. If there is no subsequent patch release, the `eol` date is aligned with the `eol` date of the corresponding stable release.
- **EOL of Latest Patch Release**: The latest patch release's `eol` date matches the `eol` date of the stable release.
- **EOL of Stable Releases**: The `eol` date for a stable release marks the end of support for that major version.

This ensures that all minor updates within a major release adhere to the same overall support timeline.

For example:

- **Stable Release `release-1312`**:
  - `released`: 2023-11-16
  - `extended`: 2024-05-03
  - `eol`: 2024-08-03
- **Patch Release `release-1312.1`**:
  - `released`: 2023-11-23
  - `eol`: 2024-01-15 (next patch release date)
- **Patch Release `release-1312.2`**:
  - `released`: 2024-01-15
  - `eol`: 2024-02-14 (next patch release date)
- ...
- **Patch Release `release-1312.7`**:
  - `released`: 2024-07-03
  - `eol`: 2024-08-03 (inherits from stable release eol)

In this example, the `eol` of `release-1312.1` is set to the `released` date of `release-1312.2`, and the `eol` of the latest patch release (`release-1312.7`) is set to the `eol` of the stable release (`release-1312`).

```
❯ ./glrd --type stable,patch | grep 'Name|1312'
Name                	Version             	Type                	Git Commit          	Release date        	Extended maintenance	End of maintenance  
release-1312        	1312                	stable              	N/A                 	2023-11-16          	2024-05-03          	2024-08-03          
release-1312.0      	1312.0              	patch               	40b9db2             	2023-11-16          	N/A                 	2023-11-23          
release-1312.1      	1312.1              	patch               	2a12736             	2023-11-23          	N/A                 	2024-01-15          
release-1312.2      	1312.2              	patch               	177c5ce             	2024-01-15          	N/A                 	2024-02-14          
release-1312.3      	1312.3              	patch               	367f95e             	2024-02-14          	N/A                 	2024-06-14          
release-1312.5      	1312.5              	patch               	9bd6f63             	2024-06-14          	N/A                 	2024-07-03          
release-1312.7      	1312.7              	patch               	330e891             	2024-07-03          	N/A                 	2024-08-03  
```

Please note that the `extended` lifecyle field is not taken into account for patch releases. This is simply an administrative date that has no technical implications.

**Comment by yeoldegrove** [comment]
https://github.com/gardenlinux/glrd hosts my proposal for a Garden Linux Release Database (GLRD).

**Comment by yeoldegrove** [comment]
https://github.com/gardenlinux/gardenlinux/pull/2409 enables GLRD for nightly and stable/patch releases.
