### ISSUE TITLE
Enhance unbase_oci

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2476]
Goal is to make unbase_oci tooling more user friendly and easy to consume for application developers

improvements:
- [x] allow passing image tags directly (with tag like docker://my-image:latest, make it similar to https://github.com/containers/skopeo?tab=readme-ov-file#copying-images)
 Example usage: `./unbase_oci --ldd-dependencies ghcr.io/gardenlinux/gardenlinux:1592 ghcr.io/gardenlinux/glvd-api:latest  ghcr.io/gardenlinux/glvd-api:bare`
- [x] make base image optional if it can be inferred (might not be good to do reliably) (can be set explicitly)
- [x] ~have default name for bare image (can be set explicitly)
Example usage: `./unbase_oci --ldd-dependencies ghcr.io/gardenlinux/glvd-api:latest`~
-  [ ] ~generate multi-arch image by default if the input image is multi-arch (like gl image, latest tag with both architectures)~

**Comment by nkraetzschmar** [comment]
> make base image optional if it can be inferred (might not be good to do reliably) (can be set explicitly)

this could probably be done something like this:

```shell
#!/usr/bin/env bash

set -eufo pipefail

image="$1"
parent="$(podman image inspect "$image" | jq -r '.[0] | .Parent')"
repo_tag="null"
while [ "$repo_tag" == null ]; do
	if [ -z "$parent" ]; then
		echo "failed to determine base image" >&2
		exit 1
	fi
	repo_tag="$(podman image inspect "$parent" | jq -r '.[0] | .RepoTags.[0]')"
	parent="$(podman image inspect "$parent" | jq -r '.[0] | .Parent')"
done

echo "$repo_tag"
```

It will obviously only work if the base image and all images along the parent chain from input to base are available locally.

I tested that it works with a multistage Containerfile like the following:

```Containerfile
FROM debian AS base
RUN apt-get update

FROM fedora AS rnd
RUN head -c 1M /dev/urandom > /rnd

FROM base
RUN id
COPY --from=rnd /rnd /rnd
RUN ls -lah /
```

In this case it correctly reports the base image as `docker.io/library/debian:latest`

Can anyone think of cases where this wont work? besides the obvious one where there simply aren't multiple layers (squashed or output from our builder)

**Comment by nkraetzschmar** [comment]
> make base image optional if it can be inferred (might not be good to do reliably) (can be set explicitly)
> [...]
> have default name for bare image (can be set explicitly) Example usage: `./unbase_oci --ldd-dependencies ghcr.io/gardenlinux/glvd-api:latest`

Having these two option together would make it ambiguous which positional arg refers to which image input if there are 2.
Consider the case `./unbase_oci --ldd-dpendencies podman:imageA podman:imageB` would this resolve to

```
base=imageA
input=imageB
output={auto determined}
```

OR

```
base={auto determined}
input=imageA
output=imageB
```

To avoid any confusion on which positional arg does what, I'd propose using an explicit `auto` value for the base image and always requiring to specify the output (default here would be hard to pick, since some might like `:unbase_oci`, `:bare`, or `:distroless` as the tag, there really isn't a good convention).

Maybe we can allow output syntax of the form `:${tag}`, where this implies, that the output is equal to `${input}:${tag}`

**Comment by nkraetzschmar** [comment]
allow only specifying the tag of the output image:
✅  https://github.com/gardenlinux/unbase_oci/commit/52f173ebbe9ca413a5bb5c7d506ae86c74386437

as a side effect this also work for the input image, so syntax like the following:

```
./unbase_oci podman:gardenlinux:base :sapmachine :sapmachine_unbased
```

is now equivalent to

```
./unbase_oci podman:gardenlinux:base podman:gardenlinux:sapmachine podman:gardenlinux:sapmachine_unbased
```

if any positional arg begins with `:` it copies the previous positional arg just replacing the tag

**Comment by nkraetzschmar** [comment]
> make base image optional if it can be inferred (might not be good to do reliably) (can be set explicitly)

✅ https://github.com/gardenlinux/unbase_oci/commit/ea1243f2f2dbf6926b3ab90332b65ba9dfd3fda5

**Comment by nkraetzschmar** [comment]
> generate multi-arch image by default if the input image is multi-arch (like gl image, latest tag with both architectures)

Building multi-arch images can't be done fully locally. This always involves some interaction with a repository, by first pushing each arch individually and then assembling the multi-arch manifest using the registries digests for each image.

Podman for example will also always only pull one arch of any given image and untag it if a different arch is pulled later.

We could maybe do some trickery with skopeo instead of using podman, but that would break the auto base determining feature. Therefore, unless someone has ideas to work around this, it appears unfeasible to add multi-arch support into unbase_oci.

**Comment by fwilhe** [comment]
Tried to use it here https://github.com/gardenlinux/glvd-api/pull/57/files

Q on multi-arch images: You can see in above PR how I did that previously by pulling the images for the specific arch and that seems to have worked. Is this not possible with the new way? I've tried multiple ways but none of them seems to really work. IMO this would be important. I'm fine if we don't build a real multi-arch manifest, but being able to build for amd and arm both in ci and on a developer laptop would be important imo.

**Comment by nkraetzschmar** [comment]
arch flag in unbase_oci won't really work, as the local tags in your container engine are always only single arch. we are only exporting what is already in your container engines image store (otherwise the whole auto determine base won't work anyways).

So to build for a given arch just build the image with `podman build --arch arm64 -t target`
And then run `./unbase_oci --ldd-dependencies auto podman:target :unbased`

Building with arch set will also (at least with new podman versions) fetch the correct version of the images used in `FROM` lines. For older versions of podman you might need to `podman pull --arch arm64 ${base}` first as otherwise it might create some frankenstein image partly one arch, partly another.
