### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by makeItFuckingSustainable** [gardenlinux/gardenlinux#32]
**What would you like to be added**:

Currently it is unclear how to enable gpu support on a gardenlinux node.
Please provide a clear guide how gpus can be used on gardenlinux nodes.
Possible solutions we would see are:
- providing a dedicated gardenlinux image with baked in nvidia gpu support
- enabling a daemonset approach along the lines of the nvidia/gpu-operator https://github.com/NVIDIA/gpu-operator

**Why is this needed**:

Since CoreOS is deprecated and gardener does not Ubuntu support in the SAP live landscape, it is in the near future not possible (or not straight forward) to use gpus gardener clusters in the SAP live landscape.
Thereby all workloads that rely on gpu resources cannot be served on the above gardener clusters anymore when the CoreOS support is dropped.

**Comment by marwinski** [comment]
Sorry for the delay. We currently have a team looking at this. We don't expect any changes in the Garden Linux release due to this - we expect it to work more or less out of the box.

**Comment by marwinski** [comment]
I know that it works and GPU support has been provided. Two questions:

- is this documented so other users can use it? 
- is the Garden Linux team doing enough to support this effort and if not what could be done?

**Comment by Vincinator** [comment]
Closing. We are working on delivery of kernel module build container. These build container have the matching kernel sources, debug symbols and headers installed. This enables us to provide driver support for selected driver versions. Please open an issue if you have a certain driver in mind.

Delivery of build container depends on the garden linux base image, since we want to base the build environment on gardenlinux if we distribute it. However, you may find an early version of the build container here: https://github.com/gardenlinux/gardenlinux/tree/main/container/build-kernelmodule
