### ISSUE TITLE
Add Garden Linux image flavour for hypervisor generation V2 [Azure]

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#345]
**What would you like to be added**:

As a user I want to create Garden Linux images for hypervisor generation V2. 

**Why is this needed**:

See https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2

**Comment by marwinski** [comment]
This is getting more urgent as gen2 has instance types that are not supported with gen1.

**Comment by MrBatschner** [comment]
Docs: https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2

**Comment by chrinorse** [comment]
I tested the azure garden linux image with HyperV generation 2, it works out of the box. Generation 2 images use uefi boot and SCSI, both is available in the garden linux azure image. I also tried to enable secure boot, but that fails with a "*Your virtual machine is prevented from booting due to secure boot validation failure. This could be due to unsigned boot components.*" message.

**Comment by chrinorse** [comment]
Note for secure boot: As mentioned in the other comment, secure boot is currently not working with garden linux and azure. The keys used for signing the garden linux boot image are unknown to azure.
