### ISSUE TITLE
file.exclude has problems on delete

### ISSUE THREAD

**Issue by gehoern** [gardenlinux/gardenlinux#463]
there are errors on deleting directories in file.exclude.

it seems directories are not deleted but i guess this is a problem as it is only a file list and no handling of fully empty directories or file-only deletes is possible!

proposing following file handling

`/some/filepath` -> delete the file filepath (if it is a directory = error)
`/some/dirpath/` -> deleting some empty directory named dirpath (if is is a file = error, if it is not empty = error)
`/some/dirpath/*` -> delete all content of directory dirpath if it is a file or an empty directory (dirpath is not deleted)
`/some/dirpath/**` -> delete all content of directory dirpath including directories with content (dirpath is not deleted)

**Comment by waldiTM** [comment]
Why so complex? What would break if it always does a recursive removal?

**Comment by waldiTM** [comment]
Oh. Is it called `file.exclude` or `files.exclude`? I see both.

**Comment by gehoern** [comment]
Where? I can only fine file.exclude which is right!

**Comment by nanory** [comment]
Hi @gehoern ,

we could also enable this by performing a recursive removal on directories. We would only need to adjust `bin/garden-config` from this:
```
for j in $(cat $featureDir/$i/file.exclude); do
    rm -f $targetDir$j || true
done
```
to this (adding -r parameter):
```
for j in $(cat $featureDir/$i/file.exclude); do
    rm -fr $targetDir$j || true
done
```
This ensures, that directories are deleted properly. I tested it and the referenced directory from file.exclude has been removed successfully. 

Is this feasible or should we still implement the proposed handling mentioned in your first comment?

**Comment by nanory** [comment]
There are reasons to harden the removal by not using the `-r` parameter, so that the removal must be configured explicitly instead of relying on an implicit removal that may removes files unintentionally.

However, by using `-r`, the build also removes files that are not required since the build would probably fail later on, if they were needed. By using the `-r` parameter, this helps to keep the image clean.

Therefore, we would use the `-r` parameter for now.
