### ISSUE TITLE
grow-root should be disabled for physical machines

### ISSUE THREAD

**Issue by 5kt** [gardenlinux/gardenlinux#501]
Growing the root partition to maximum possible size should be disabled on metal machines and be allowed only on virtual environments.

**Comment by gehoern** [comment]
Look at #102

**Comment by Vincinator** [comment]
Growing root partition is currently disabled for `metal` targets.

I think the installer (#495) should be the default option for the user to specify the partitions.

**Comment by gehoern** [comment]
it seems this is disabled but i think since we use repart in #102 this is no problem anymore and can be activated.

nice sideffect: you can just dd gardenlinux on a physical disk and it would just use the disk on next reboot. If you would need a more complex setup use the installer script instead of dd. (Then repart would make no sense but it does not cost a thing).

**Comment by chrinorse** [comment]
It is disabled on metal. ```systemd-repart``` is installed, but no configuration is added. Since there is no configuration systemd-repart is not executed and no partition is resized.
