### ISSUE TITLE
network config should be merged into one file

### ISSUE THREAD

**Issue by waldiTM** [gardenlinux/gardenlinux#598]
Currently the network config is shipped in two files that only differ in the name match:
- `./features/server/file.include/etc/systemd/network/en.network`
- `./features/server/file.include/etc/systemd/network/eth.network`

As `.network` file can have multiple name matches at once, those should be merged.

At the same time, it should be better named, like `90-default.network` and make the override of `91-default.network` not longer necessary.

**Comment by nanory** [comment]
@5kt Is `91-default.network` still existing in dracut? 
After discussing this with @gehoern, we will rename those files to `zz-default.network`

**Comment by waldiTM** [comment]
> After discussing this with @gehoern, we will rename those files to `zz-default.network`.

I wonder where you came up with that `zz`. Even systemd itself always uses something in `90` to `99` for it's defaults.

**Comment by nanory** [comment]
> I wonder where you came up with that `zz`. Even systemd itself always uses something in `90` to `99` for it's defaults.

The idea behind calling this configuration `zz-default.conf` is that whatever configuration is provided by another feature or another user, they will usually overwrite the provided configuration. I think the assumption is, that administrators usually tend to use systemd configuration names between `00` and `99`, so that `zz-default.conf` would always be overwritten once a user is defining a configuration there.

It's basically the bare minimum configuration needed but will probably be overwritten elsewhere.

**Comment by nanory** [comment]
As discussed today, we will rename this file to `99-default.conf` in order to stick to the systemd naming convention.
