### ISSUE TITLE
Enhance Documentation

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#608]
**What would you like to be added**:
I think we need to enhance the current documentation with much more content regarding debugging, '$image-dev' version, how to use images, contact / community (e.g. Gitter) information, etc.

**Why is this needed**:
This should help new users starting with Garden Linux. Therefore, we can adjust the current README as well as use the GitHub Wiki for this project.

Therefore, we should cover at least:

**TOC:**
 * Overview
   * Motivation
   * Garden Linux Core
 * Features
 * Building
   * Overview
   * Requirements
   * Adjust Build Options
   * Build Images
     * GCP
     * AWS
     * [...]
   * Build Dev Images
     * GCP
     * AWS
     * [...]
   * Deploying
     * Overview
     * Cloud Images
     * ISO
     * PXE
 * Customize
   * Feature system
   * Features
   * Modifieres
   * Creating manual Builds
 * Debugging
 * FAQ
   * No space left of device while building images
   * Use different Build Options
   * [...]
 * Release
 * CI/CD - Pipeline integrations
 * Contact / Community

That's a first draft of a possible TOC. Feel free to add further topics that should be covered. We should also discuss if everything should be covered within the README or we should keep the README short and use the Wiki functionality of GitHub. I think we may cover all these points within the README.

**Comment by nanory** [comment]
Hi @florianpaulhoberg ,

one thing to keep in mind is, that Github Wikis are not part of the actual repository itself but they are created in an additional repository, as shown [here](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally).

Luckily, the documents are based on Markdown but it may be a disadvantage to have them separately (e.g. for defining Github Actions on them), so using dedicated Markdown files instead of the Wiki functionality may be the right choice for now. We should discuss this with the team but moving the Markdown files to a Github Wiki later on shouldn't be a problem.

**Comment by nanory** [comment]
Hi @gyptazy,

as discussed in previous meetings, I would suggest to use the [docs/](https://github.com/gardenlinux/gardenlinux/tree/main/docs) directory for the documentation.

As of now, this directory already contains a [README.md](https://github.com/gardenlinux/gardenlinux/blob/main/docs/README.md) as well as some directories and I think we can adapt this structure there to the suggested ToC that you have provided here.

So basically, the [docs/build/](https://github.com/gardenlinux/gardenlinux/tree/main/docs/build) directory would be equal to your suggested `Building` chapter. There is also a [docs/deployment/](https://github.com/gardenlinux/gardenlinux/tree/main/docs/build) which probably suites your `Deploying` chapter (we should maybe move this chapter up in the ToC hierarchy). 

I'm not sure about the `Features` chapter, since there is a [Features documentation](https://github.com/gardenlinux/gardenlinux/blob/main/features/README.md) that is placed in another directory. We could referenced that document or move the content from there to the [docs/](https://github.com/gardenlinux/gardenlinux/tree/main/docs) directory. That still needs to be discussed.

**Comment by dnan0s** [comment]
As far as i've talked with @Vincinator, his idea is to put a troubleshooting section inside the platform section, e.g. a section "Troubleshooting" inside docs/deployment/pxe.md, another in docs/deployment/aws.md ...

I'm fine with both, only thing i wanna avoid is many small files with very little content.

Besides that, i think the perspective of a user is rather "this doesn't work, where is troubleshooting" rather than "this (aws) doesn't work, where is build/aws // deployment/aws".

If we choose to use a central file, working with Tags might be a good idea, so strg+f can be used conveniently.

**Comment by Vincinator** [comment]
This issue must have slipped my mind. Sorry for the late reply.

> MHO we should just place a Troubleshooting.md file on the same level like FAQ within the first iteration. Maybe, we should also do this for FAQ and Debugging [...]

I agree, lets start with that. We can restructure documentation in a later iteration if necessary.

**Comment by Vincinator** [comment]
Closing this issue for now. Updated Documentation will follow, but currently @nkraetzschmar is working on a garden linux builder. This builder will enable users to define and maintain features separately (bring your own features).

This will require good documentation for users of garden linux builder, with a new set of requirements for a slightly different (more specific) target audience.
