### ISSUE TITLE
Definition of kvm image kind of useless now

### ISSUE THREAD

**Issue by waldiTM** [gardenlinux/gardenlinux#613]
**What happened**:
The `kvm` and `kvm-dev` images are now defined with
- hard immutability using `verity` and
- no container run-time.

So there is no way to install anything.

**What you expected to happen**:
Install `docker` or something like that.

**Comment by nanory** [comment]
Hi @waldiTM ,

you're right. `verity` must be moved to _readonly.

**Comment by gyptazy** [comment]
Hi @waldiTM @nanory,

I just spoke with @waldiTM - we need to discuss what we really want to achieve. I don't want to say the current *kvm-dev* packages are useless since you still may create an overlay fs for further tests but I agree that this should be as an expected default for the *kvm-dev* image. Therefore, I think we have several options:

 * We can create an overlay for this (like */var* etc. for other mnts)
 * We can move verity to feature *_readonly* and include this for needed image types
 * We can just provide docker/containerd binaries and provide a solution for executing images instead
 * Maybe other options?

IMHO, (re)moving verity from *kvm-dev* (to *_readonly*) could be an easy way to solve this. But I'd prefer a solution by using overlays. What do you think?

**Comment by nanory** [comment]
Hi @gyptazy,

as discussed in the last meeting, we will revert the fstab of the `kvm` feature, so that it doesn't contain the dm-verity functionality and ensure that the root partition is writable again.

However, since we need dm-verity, we will move it to the [_readonly](https://github.com/gardenlinux/gardenlinux/tree/main/features/_readonly) feature by doing the following steps:
* Revert to a generic fstab in the `kvm` feature again.
* Add an executable called `fstab_mod` to each modifier feature which modifies a given fstab of a plattform feature (e.g. `kvm`)  and extends it with proper fstab entries needed by the corresponding modifier.
  * In our case, this script would be part of the modifier feature `_readonly` for example.
* Integrate the script to the build pipeline, so that it is called during the creation of the rootfs.

As discussed, I'm assigning this ticket to @gehoern , which will take care of the `fstab_mod` script.

**Comment by nanory** [comment]
Hi @gehoern,

as discussed in our last meeting, a short reminder that we want to adjust the `fstab_mod` script in that way, that it ensures to set the read-write partition at the end of the fstab before it hands it over to the `makepart` script.

Thus, `fstab_mod` ensures that the read write partition can be resized properly.

Modifying this script would also resolve the issue #631 and we could probably skip the Merge Request of #673 then which tries to change the order after makepart.

**Comment by gyptazy** [comment]
https://github.com/gardenlinux/gardenlinux/pull/678 just got merged. This removed the verity feature for *kvm(-dev)* images. I'm not quite sure if we need this issue anymore. However, the reintegration of *verity* will be done within https://github.com/gardenlinux/gardenlinux/issues/679.

ping: @waldiTM @nanory

**Comment by waldiTM** [comment]
The verity feature was completely disabled for now.
