### ISSUE TITLE
Stale branches and branch naming

### ISSUE THREAD

**Issue by zobelhelas** [gardenlinux/gardenlinux#625]
**What would you like to be added**:
- [ ] Remove stale branches
- [ ] Agree on branch naming scheme

**Why is this needed**:
We currently have 37 branches, with a lot of them being stale. It would be nice if the number of branches could be reduced to a useful minimum. In addition I would like to suggest, that we try invent a naming scheme for the branches (maybe including the bug number) so we/others can easily identify which branches could be removed if stale (eg. if bug is closed, the corresponding branch does not need to stay around).

**Comment by Vincinator** [comment]
+1

I think we should start naming new branches in a structured way.
Structuring would make it easier to discover and clean up branches. 

We could use Something like: 
- `feature/<issue-id>-name-of-feature`
- `release/576.6`, `release/576.7`, ... 
- `archive/some-name` for stale branches that we need to keep for some odd reason? 
- ...
Just an example

@MrBatschner was also suggesting to use `release/<name of release>`branches instead of `rel-xyz.a`

**Comment by MrBatschner** [comment]
Yes, we are already implementing this pattern for the `release/xxx` branches (even though not for minor/patch releases - that we will still do with tags).

**Comment by Vincinator** [comment]
Additionally I think everyone can check https://github.com/gardenlinux/gardenlinux/branches/yours and rename, or delete branches

**Comment by MrBatschner** [comment]
For release branches, it makes sense to have separate branches for each major release (**576**.7), minor releases (576.**7**) however should be done via tags - otherwise we will collect way too many release branches for minor changes to the code.

**Comment by gyptazy** [comment]
Ok, let's finally make a step forward. Added docs: https://github.com/gardenlinux/gardenlinux/pull/1332
