### ISSUE TITLE
Package build for perl without libdb

### ISSUE THREAD

**Issue by waldiTM** [gardenlinux/gardenlinux#653]
**What would you like to be added**:
A package build of `perl`, which is patched to not depend on `libdb`.

**Why is this needed**:
`git` and a lot of other main Debian stuff depends on `perl`.

**Comment by gyptazy** [comment]
Ok, I have integrated this within the GitLab pipeline (see also: https://gitlab.com/gardenlinux/gardenlinux-package-perl/-/merge_requests/1). This feature just got merged. Thanks to @waldiTM for review.

jfyi @nanory (can we close this task?).

**Comment by nanory** [comment]
Hi @gyptazy,

no, please ensure that this package is released. As of now, it only has been built but not published to the Garden Linux repo. In order to achieve this, please add a Git tag to the following repo:
* https://gitlab.com/gardenlinux/gardenlinux-package-perl

The Git tag must look like this:
```
gardenlinux/5.34.0-3gardenlinux1
```

In addition, the packages list for the Garden Linux repo must be extended, otherwise the pipeline wouldn't upload the package to the repo. Please extend this list:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/dev/gardenlinux-include

We must ensure that Berkeley DB source packages and source packages that rely on it, are not available as well, so you must extend this list, too:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/dev/debian-exclude

After that, we should be able to install the modified `perl` package in our Garden Linux images. If this is the case, we can close this issue.

**Comment by nanory** [comment]
Hi @gyptazy,

the Git tag has been added by @waldiTM as you can see here:
* https://gitlab.com/gardenlinux/gardenlinux-package-perl/-/tree/gardenlinux/5.34.0-3gardenlinux1

Moreover, the package lists have been adjusted as well, so we can probably close this issue.

**Comment by gyptazy** [comment]
LGTM, thanks for working on this during my vacation.

Pkg-perl: https://gitlab.com/gardenlinux/gardenlinux-package-perl/-/merge_requests/1
Tag: https://gitlab.com/gardenlinux/gardenlinux-package-perl/-/tags/gardenlinux%2F5.34.0-3gardenlinux1
Pkg-include: https://gitlab.com/gardenlinux/gardenlinux-package-build/-/commit/567109618d23971136a4c491d3959dde07141071
