### ISSUE TITLE
present `apt` package too old

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#744]
**What happened**:
Installing the package `apt-utils` in `bookworm` fails with dependency issues to `apt` where:

installed/pinned: 2.4.3
should be: 2.4.4

```
 apt-utils : Depends: apt (= 2.4.4) but 2.4.3 is to be installed
             Depends: libapt-pkg6.0 (>= 2.4.4) but 2.4.3 is to be installed
```

```
root@garden-build:/# apt-cache policy apt
apt:
  Installed: 2.4.3
  Candidate: 2.4.3
  Version table:
     2.4.4 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages
 *** 2.4.3 900
        900 https://repo.gardenlinux.io/gardenlinux dev/main amd64 Packages
        100 /var/lib/dpkg/status
```

`apt-utils` will be installed with further unit tests like `rkhunter` and `tiger`.

**What you expected to happen**:
There shouldn't be any dependency issue.

**How to reproduce it (as minimally and precisely as possible)**:
This can be reproduced by just building any image from scratch (via `main` branch).

**Anything else we need to know**:

**Environment**:

**Comment by nanory** [comment]
Hi @gyptazy ,

I tried to analyze the issue and it seems that the corresponding package pipeline seems to have a problem. It wasn't able to publish the newest packages since three days:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/pipelines/508111101

After taking a quick look into the code, it seems that the following `aptly` command causes the issue because usually it should detect that the aptly snapshot `v1:baseos:dev:debian:bookworm` exists and move it (backup it), so that a new snapshot can be created with the same name:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/bin/garden-repo-mirror-debian#L47-54
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/bin/garden-repo-common.sh#L180-188

However, this isn't the case. Since it's hard to tell from the output, what issue `aptly` has in detail, I ask @damyan to help me analyzing the output on the corresponding Gitlab Runner.

I will update you once I have some more information to share.

**Comment by nanory** [comment]
Hi @gyptazy,

we found the issue for the failed `publish today` job, which prevents the update of the `apt` package in Garden Linux. The issue gets fixed once the following PR has been merged:
* https://gitlab.com/gardenlinux/gardenlinux-package-build/-/merge_requests/66 

More information about the bug itself can be found in the corresponding PR and its issue.

**Comment by nanory** [comment]
Hi @gyptazy,

the PR got merged and the Garden Linux Repo is up to date now. I also checked, if the `tiger` and `rkhunter` tests are working again and indeed, the tests are working, too.

I tested it with the `kvm-dev` build:
```
test rkhunter is enabled by the following features: base 
OK - rkhunter didn't detect any issues
passed
...
test tiger is enabled by the following features: server base 
OK - tiger didn't detect any issues
passed
```

As  a result, this issue has been solved.
